export const database = [
  {
    "name": 'Dayarambhai',
    "value": '1',
    "sex": 'male',
    "level": '1',
    "home": 'Gathaman',
    "dateOfBirth": null,
    "spouceDateOfBirth": null,
    "spouce": 'Ambaben',
    "spouceAge": 0,
    "spouceHome": 'No clue',
    "imagePath": null,
    "imagePathSpouse": null,
    "items": [
      {
        "name": 'Dhanabhai',
        "value": 2,
        "sex": 'male',
        "level": '2',
        "home": 'Gathaman',
        "dateOfBirth": null,
        "spouceDateOfBirth": null,
        "spouce": 'Menaben',
        "spouceAge": 0,
        "spouceHome": 'Gathaman',
        "imagePath": null,
        "imagePathSpouse": null,
        "items": [
          {
            "name": 'Hiraben',
            "value": 3,
            "sex": 'female',
            "level": '2.1',
            "home": 'Chandisar',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Nanjibhai Khemabhai',
            "spouceAge": 0,
            "spouceHome": 'Chandisar',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Gangaben',
                "value": 4,
                "sex": 'female',
                "level": '2.1.1',
                "home": 'No clue',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Amaratbhai',
                "value": 5,
                "sex": 'male',
                "level": '2.1.2',
                "home": 'Chandisar',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Narmadaben',
                "value": 6,
                "sex": 'female',
                "level": '2.1.3',
                "home": 'No clue',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Ashokbhai',
                "value": 7,
                "sex": 'male',
                "level": '2.1.4',
                "home": 'Chandisar',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Ishvabhai',
                "value": 8,
                "sex": 'male',
                "level": '2.1.5',
                "home": 'Chandisar',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Maheshbhai',
                "value": 9,
                "sex": 'male',
                "level": '2.1.6',
                "home": 'Chandisar',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
            ],
          },
          {
            "name": 'Dalajibhai',
            "value": 10,
            "sex": 'male',
            "level": '2.2',
            "home": 'Gathaman',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Shantaben',
            "spouceAge": 0,
            "spouceHome": 'Chandisar',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Yogeshbhai(Natubhai)',
                "value": 11,
                "sex": 'male',
                "level": '2.2.1',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Madhuben',
                "spouceAge": 0,
                "spouceHome": 'Lukhasan',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Maitri(Bittu)',
                    "value": 12,
                    "sex": 'female',
                    "level": '2.2.1.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Dev',
                    "value": 13,
                    "sex": 'male',
                    "level": '2.2.1.2',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Karan',
                    "value": 14,
                    "sex": 'male',
                    "level": '2.2.1.3',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Ramilaben',
                "value": 15,
                "sex": 'female',
                "level": '2.2.2',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Karasandas',
                "spouceAge": 0,
                "spouceHome": 'Palanpur',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Anjali',
                    "value": 16,
                    "sex": 'female',
                    "level": '2.2.2.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Pushpaben',
                "value": 17,
                "sex": 'female',
                "level": '2.2.3',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Dheerajkumar',
                "spouceAge": 0,
                "spouceHome": 'Zakha',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Yash',
                    "value": 18,
                    "sex": 'male',
                    "level": '2.2.3.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
            ],
          },
          {
            "name": 'Jiviben',
            "value": 19,
            "sex": 'female',
            "level": '2.3',
            "home": 'Megalvas, Palanpur',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Shankarbhai',
            "spouceAge": 0,
            "spouceHome": 'Palanpur',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Pareshbhai',
                "value": 20,
                "sex": 'male',
                "level": '2.3.1',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Anitaben',
                "spouceAge": 0,
                "spouceHome": 'Palanpur',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Surbhi',
                    "value": 104,
                    "sex": 'female',
                    "level": '2.3.1.1',
                    "home": 'Palanpur',
                    "dateOfBirth": '1999-06-13T00',
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Rishabh',
                    "value": 105,
                    "sex": 'male',
                    "level": '2.3.1.2',
                    "home": 'Palanpur',
                    "dateOfBirth": '1999-06-13T00',
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Bhartiben',
                "value": 21,
                "sex": 'female',
                "level": '2.3.2',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Kanubhai Khadaliya',
                "spouceAge": 0,
                "spouceHome": 'Palanpur',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Priyanka',
                    "value": 22,
                    "sex": 'female',
                    "level": '2.3.2.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": 'Abhishek',
                    "spouceAge": 0,
                    "spouceHome": 'Palanpur',
                    "imagePath": null,
                    "imagePathSpouse": null,
                    "items": [
                      {
                        "name": 'Parv',
                        "value": 23,
                        "sex": 'male',
                        "level": '2.3.2.1.1',
                        "home": 'Palanpur',
                        "dateOfBirth": null,
                        "spouceDateOfBirth": null,
                        "spouce": '',
                        "spouceAge": 0,
                        "spouceHome": 'No clue',
                        "imagePath": null,
                        "imagePathSpouse": null,
                      },
                    ],
                  },
                ],
              },
              {
                "name": 'Atulbhai',
                "value": 24,
                "sex": 'male',
                "level": '2.3.3',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Pinkyben',
                "spouceAge": 0,
                "spouceHome": 'Radhanpur',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Om',
                    "value": 25,
                    "sex": 'male',
                    "level": '2.3.3.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Kavya',
                    "value": 26,
                    "sex": 'female',
                    "level": '2.3.3.2',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
            ],
          },
          {
            "name": 'Hirabhai',
            "value": 27,
            "sex": 'male',
            "level": '2.4',
            "home": 'Gathaman',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Shantaben',
            "spouceAge": 0,
            "spouceHome": 'Madana',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Poonam',
                "value": 28,
                "sex": 'female',
                "level": '2.4.1',
                "home": 'Changvada',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Hiteshkumar',
                "spouceAge": 0,
                "spouceHome": 'Surat',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Parth',
                    "value": 29,
                    "sex": 'male',
                    "level": '2.4.1.1',
                    "home": 'Surat',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
            ],
          },
          {
            "name": 'Narbhiben',
            "value": 30,
            "sex": 'female',
            "level": '2.5',
            "home": 'Malan',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Shankarbhai',
            "spouceAge": 0,
            "spouceHome": 'Malan',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Kalpeshbhai',
                "value": 31,
                "sex": 'male',
                "level": '2.5.1',
                "home": 'Malan',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Kuntal',
                "value": 106,
                "sex": 'male',
                "level": '2.5.2',
                "home": 'Malan',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": '',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Dipika',
                "value": 107,
                "sex": 'female',
                "level": '2.5.3',
                "home": 'Malan',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
            ],
          },
          {
            "name": 'Bhagvanbhai',
            "value": 32,
            "sex": 'male',
            "level": '2.6',
            "home": 'Gathaman',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Savitaben',
            "spouceAge": 0,
            "spouceHome": 'Palanpur',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Manishaben',
                "value": 33,
                "sex": 'female',
                "level": '2.6.1',
                "home": 'Jalotra',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Kamleshkumar',
                "spouceAge": 0,
                "spouceHome": 'Jalotra',
                "imagePath": null,
                "imagePathSpouse": null,
              },
              {
                "name": 'Satish',
                "value": 34,
                "sex": 'male',
                "level": '2.6.2',
                "home": 'Surat',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Niruben',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Jainil',
                    "value": 35,
                    "sex": 'male',
                    "level": '2.6.2.1',
                    "home": 'Surat',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Pradeep',
                "value": 36,
                "sex": 'male',
                "level": '2.6.3',
                "home": 'Surat',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Divam',
                    "value": 37,
                    "sex": 'male',
                    "level": '2.6.3.1',
                    "home": 'Surat',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Hetalben',
                "value": 38,
                "sex": 'female',
                "level": '2.6.4',
                "home": 'Tavadiya',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'Tavadiya',
                "imagePath": null,
                "imagePathSpouse": null,
              },
            ],
          },
          {
            "name": 'Narmadaben',
            "value": 39,
            "sex": 'female',
            "level": '2.7',
            "home": 'Takarvada',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Virchanddas',
            "spouceAge": 0,
            "spouceHome": 'Takarvada',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Sonalben',
                "value": 40,
                "sex": 'female',
                "level": '2.7.1',
                "home": 'Mithivav, Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Maheshkumar',
                "spouceAge": 0,
                "spouceHome": 'Mithivav, Palanpur',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Bhavya',
                    "value": 41,
                    "sex": 'male',
                    "level": '2.7.1.1',
                    "home": 'Mithivav, Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Krithi',
                    "value": 42,
                    "sex": 'female',
                    "level": '2.7.1.2',
                    "home": 'Mithivav, Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Nimisha',
                "value": 108,
                "sex": 'female',
                "level": '2.7.2',
                "home": 'Takarvada',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'No clue',
                "spouceAge": 0,
                "spouceHome": 'No clue',
                "imagePath": null,
                "imagePathSpouse": null,
              },
            ],
          },
          {
            "name": 'Dineshbhai',
            "value": 43,
            "sex": 'male',
            "level": '2.8',
            "home": 'Gathaman',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Vimuben',
            "spouceAge": 0,
            "spouceHome": 'Kotda',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Kalpanaben',
                "value": 44,
                "sex": 'female',
                "level": '2.8.1',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Bipinkumar',
                "spouceAge": 0,
                "spouceHome": 'Meta',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Het',
                    "value": 45,
                    "sex": 'male',
                    "level": '2.8.1.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Piyush',
                "value": 46,
                "sex": 'male',
                "level": '2.8.2',
                "home": 'Gathaman',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": '',
                "spouceAge": 0,
                "spouceHome": 'Meta',
                "imagePath": null,
                "imagePathSpouse": null,
              },
            ],
          },
        ],
      },
      {
        "name": 'Chelabhai',
        "value": 47,
        "sex": 'male',
        "level": '3',
        "home": 'Kailashnagar, Palanpur',
        "dateOfBirth": null,
        "spouceDateOfBirth": null,
        "spouce": 'Shantaben',
        "spouceAge": 0,
        "spouceHome": 'Megalvas, Palanpur',
        "imagePath": null,
        "imagePathSpouse": null,
        "items": [
          {
            "name": 'Devabhai',
            "value": 48,
            "sex": 'male',
            "level": '3.1',
            "home": 'Kailashnagar, Palanpur',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Shantaben',
            "spouceAge": 0,
            "spouceHome": 'Megalvas, Palanpur',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Hiteshbhai',
                "value": 49,
                "sex": 'male',
                "level": '3.1.1',
                "home": 'Kailashnagar, Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Ramilaben',
                "spouceAge": 0,
                "spouceHome": 'Chadotar',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Tushar(Pintu)',
                    "value": 50,
                    "sex": 'male',
                    "level": '3.1.1.1',
                    "home": 'Kailashnagar, Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Daksh',
                    "value": 51,
                    "sex": 'male',
                    "level": '3.1.1.2',
                    "home": 'Kailashnagar, Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Minaben',
                "value": 52,
                "sex": 'female',
                "level": '3.1.2',
                "home": 'Surat',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Anilkumar',
                "spouceAge": 0,
                "spouceHome": 'Chadotar',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Hinal',
                    "value": 53,
                    "sex": 'male',
                    "level": '3.1.2.1',
                    "home": 'Surat',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Varshil',
                    "value": 54,
                    "sex": 'male',
                    "level": '3.1.2.2',
                    "home": 'Surat',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Ranjanben',
                "value": 55,
                "sex": 'female',
                "level": '3.1.3',
                "home": 'Tharad',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Bharatkumar',
                "spouceAge": 0,
                "spouceHome": 'Tharad',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Krupa',
                    "value": 56,
                    "sex": 'female',
                    "level": '3.1.3.1',
                    "home": 'Tharad',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Pranav',
                    "value": 57,
                    "sex": 'male',
                    "level": '3.1.3.2',
                    "home": 'Tharad',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Sunilbhai',
                "value": 58,
                "sex": 'male',
                "level": '3.1.4',
                "home": 'Kailashnagar, Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Vimuben',
                "spouceAge": 0,
                "spouceHome": 'Mahi',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Nisarg',
                    "value": 59,
                    "sex": 'male',
                    "level": '3.1.4.1',
                    "home": 'Kailashnagar, Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Jaydeep',
                    "value": 60,
                    "sex": 'male',
                    "level": '3.1.4.2',
                    "home": 'Kailashnagar, Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        "name": 'Gamanbhai',
        "value": 61,
        "sex": 'male',
        "level": '4',
        "home": 'Gathaman',
        "dateOfBirth": null,
        "spouceDateOfBirth": null,
        "spouce": 'Navaben',
        "spouceAge": 74,
        "spouceHome": 'Kant',
        "imagePath": null,
        "imagePathSpouse": null,
        "items": [
          {
            "name": 'Diviben',
            "value": 62,
            "sex": 'female',
            "level": '4.1',
            "home": 'Mumbai',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Khushalbhai',
            "spouceAge": 0,
            "spouceHome": 'Sagrosana',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Dineshbhai',
                "value": 63,
                "sex": 'male',
                "level": '4.1.1',
                "home": 'Mumbai',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Minaben',
                "spouceAge": 0,
                "spouceHome": 'Palanpur',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Harshil',
                    "value": 64,
                    "sex": 'male',
                    "level": '4.1.1.1',
                    "home": 'Mumbai',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Sneha',
                    "value": 65,
                    "sex": 'female',
                    "level": '4.1.1.2',
                    "home": 'Mumbai',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Mukeshbhai',
                "value": 66,
                "sex": 'male',
                "level": '4.1.2',
                "home": 'Mumbai',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Dharaben',
                "spouceAge": 0,
                "spouceHome": 'Laxmipura',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Hetu',
                    "value": 67,
                    "sex": 'female',
                    "level": '4.1.2.1',
                    "home": 'Mumbai',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Ishita',
                    "value": 68,
                    "sex": 'female',
                    "level": '4.1.2.2',
                    "home": 'Mumbai',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Anitaben',
                "value": 69,
                "sex": 'male',
                "level": '4.1.3',
                "home": 'Mumbai',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Pravinkumar',
                "spouceAge": 0,
                "spouceHome": 'Gagalasan',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Dhruv',
                    "value": 70,
                    "sex": 'male',
                    "level": '4.1.3.1',
                    "home": 'Mumbai',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Sujal',
                    "value": 71,
                    "sex": 'male',
                    "level": '4.1.3.2',
                    "home": 'Mumbai',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
            ],
          },
          {
            "name": 'Hargovindbhai',
            "value": 72,
            "sex": 'male',
            "level": '4.2',
            "home": 'Gathaman',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Nayanaben',
            "spouceAge": 0,
            "spouceHome": 'Sagrosana',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Nitinbhai',
                "value": 73,
                "sex": 'male',
                "level": '4.2.1',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Archanaben',
                "spouceAge": 0,
                "spouceHome": 'Meta',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Vanshika',
                    "value": 74,
                    "sex": 'female',
                    "level": '4.2.1.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Nirav',
                "value": 75,
                "sex": 'male',
                "level": '4.2.2',
                "home": 'Gathaman',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Nikitaben',
                "spouceAge": 0,
                "spouceHome": 'Tenivada',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Heer',
                    "value": 76,
                    "sex": 'female',
                    "level": '4.2.2.1',
                    "home": 'Gathaman',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": 'No clue',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Pravinaben',
                "value": 77,
                "sex": 'female',
                "level": '4.2.3',
                "home": 'Palanpur',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Jayeshkumar',
                "spouceAge": 0,
                "spouceHome": 'Majadar',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Preksha(Pari)',
                    "value": 78,
                    "sex": 'female',
                    "level": '4.2.3.1',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Neel',
                    "value": 79,
                    "sex": 'male',
                    "level": '4.2.3.2',
                    "home": 'Palanpur',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
            ],
          },
          {
            "name": 'Prabhubhai',
            "value": 80,
            "sex": 'male',
            "level": '4.3',
            "home": 'Palanpur',
            "dateOfBirth": '1963-01-16T00',
            "spouceDateOfBirth": '1967-01-04T00',
            "spouce": 'Bharatiben',
            "spouceAge": 53,
            "spouceHome": 'Mithivav, Palanpur',
            "imagePath": require('../src/images/80.png'),
            "imagePathSpouse": require('../src/images/80S.png'),
            "items": [
              {
                "name": 'Vipul',
                "value": 81,
                "sex": 'male',
                "level": '4.3.1',
                "home": 'Canada',
                "dateOfBirth": '1989-12-13T00',
                "spouceDateOfBirth": '1989-08-01T00',
                "spouce": 'Harnisha',
                "spouceAge": 31,
                "spouceHome": 'Junagadh',
                "imagePath": require('../src/images/81.png'),
                "imagePathSpouse": require('../src/images/81S.png'),

                "items": [
                  {
                    "name": 'Viha',
                    "value": 82,
                    "sex": 'female',
                    "level": '4.3.1.1',
                    "home": 'Canada',
                    "dateOfBirth": '2020-04-24T00',
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": require('../src/images/82.png'),
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Vishal',
                "value": 83,
                "sex": 'male',
                "level": '4.3.2',
                "home": 'Australia',
                "dateOfBirth": '1991-07-09T00',
                "spouceDateOfBirth": '1991-01-19T00',
                "spouce": 'Sonali',
                "spouceAge": 29,
                "spouceHome": 'Palanpur',

                "imagePath": require('../src/images/83.png'),
                "imagePathSpouse": require('../src/images/83S.png'),
              },
              {
                "name": 'Chirag',
                "value": 84,
                "sex": 'male',
                "level": '4.3.3',
                "home": 'Rajpipla',
                "dateOfBirth": '1994-01-19T00',
                "spouceDateOfBirth": '1996-05-02T00',
                "spouce": 'Pooja',
                "spouceAge": 24,
                "spouceHome": 'Vadgam',
                "imagePath": require('../src/images/84.png'),
                "imagePathSpouse": require('../src/images/84S.png'),
              },
            ],
          },
          {
            "name": 'Madhuben',
            "value": 85,
            "sex": 'female',
            "level": '4.4',
            "home": 'Kotda',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'Dahyalal',
            "spouceAge": 0,
            "spouceHome": 'Kotda',
            "imagePath": null,
            "imagePathSpouse": null,
            "items": [
              {
                "name": 'Divyeshbhai(Deepakbhai)',
                "value": 86,
                "sex": 'male',
                "level": '4.4.1',
                "home": 'Kotda',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Bhartiben',
                "spouceAge": 0,
                "spouceHome": 'Pirojpura',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Trusha',
                    "value": 87,
                    "sex": 'female',
                    "level": '4.4.1.1',
                    "home": 'Kotda',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Zeel',
                    "value": 88,
                    "sex": 'male',
                    "level": '4.4.1.2',
                    "home": 'Kotda',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Bharatbhai',
                "value": 89,
                "sex": 'male',
                "level": '4.4.2',
                "home": 'Kotda',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Kapilaben',
                "spouceAge": 0,
                "spouceHome": 'Changvada',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Mahi',
                    "value": 90,
                    "sex": 'female',
                    "level": '4.4.2.1',
                    "home": 'Kotda',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                  {
                    "name": 'Ishani',
                    "value": 91,
                    "sex": 'female',
                    "level": '4.4.2.2',
                    "home": 'Kotda',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
              {
                "name": 'Binaben',
                "value": 92,
                "sex": 'female',
                "level": '4.4.3',
                "home": 'Gandhinagar',
                "dateOfBirth": null,
                "spouceDateOfBirth": null,
                "spouce": 'Ronakkumar',
                "spouceAge": 0,
                "spouceHome": 'Gandhinagar',
                "imagePath": null,
                "imagePathSpouse": null,
                "items": [
                  {
                    "name": 'Vihan',
                    "value": 93,
                    "sex": 'male',
                    "level": '4.4.3.1',
                    "home": 'Gandhinagar',
                    "dateOfBirth": null,
                    "spouceDateOfBirth": null,
                    "spouce": '',
                    "spouceAge": 0,
                    "spouceHome": '',
                    "imagePath": null,
                    "imagePathSpouse": null,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        "name": 'Avaliben',
        "value": 94,
        "sex": 'female',
        "level": '5',
        "home": 'Gathaman',
        "dateOfBirth": null,
        "spouceDateOfBirth": null,
        "spouce": 'No clue',
        "spouceAge": 0,
        "spouceHome": 'Madana',
        "imagePath": null,
        "imagePathSpouse": null,
        "items": [
          {
            "name": 'Kanjibhai',
            "value": 95,
            "sex": 'male',
            "level": '5.1',
            "home": 'Takarvada',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Kevalbhai',
            "value": 96,
            "sex": 'male',
            "level": '5.2',
            "home": 'Takarvada',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Ganeshbhai',
            "value": 97,
            "sex": 'male',
            "level": '5.3',
            "home": 'Takarvada',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Menaben',
            "value": 98,
            "sex": 'female',
            "level": '5.4',
            "home": 'No clue',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Ambarambhai',
            "value": 99,
            "sex": 'male',
            "level": '5.5',
            "home": 'Mumbai',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Jamanaben',
            "value": 100,
            "sex": 'fmale',
            "level": '5.6',
            "home": 'No clue',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Chamanbhai',
            "value": 101,
            "sex": 'male',
            "level": '5.7',
            "home": 'Takarvada',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Narmadaben',
            "value": 102,
            "sex": 'female',
            "level": '5.8',
            "home": 'No clue',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
          {
            "name": 'Vasantbhai',
            "value": 103,
            "sex": 'male',
            "level": '5.9',
            "home": 'Palanpur',
            "dateOfBirth": null,
            "spouceDateOfBirth": null,
            "spouce": 'No clue',
            "spouceAge": 0,
            "spouceHome": 'No clue',
            "imagePath": null,
            "imagePathSpouse": null,
          },
        ],
      },
    ],
  },
];
// last "value":106
