export const database = [
  //   {
  //     name: 'Cheese',
  //     value: 'cheese-value',
  //   },
  {
    name: 'Dayarambhai',
    value: '1',
    sex: 'male',
    level: '1',
    home: 'Gathaman',
    dateOfBirth: '',
    spouceDateOfBirth: '',
    spouce: 'Ambaben',
    spouceAge: 0,
    spouceHome: 'No clue',
    imagePath: '',
    imagePathSpouse: '',
    items: [
      {
        name: 'Dhanabhai',
        value: '2',
        sex: 'male',
        age: 0,
        level: '2',
        home: 'Gathaman',
        spouce: 'Menaben',
        spouceAge: 0,
        spouceHome: 'Gathaman',
        items: [
          {
            name: 'Hiraben',
            value: '3',
            sex: 'female',
            age: 0,
            level: '2.1',
            home: 'Chandisar',
            spouce: 'Nanjibhai Khemabhai',
            spouceAge: 0,
            spouceHome: 'Chandisar',
            items: [
              {
                name: 'Gangaben',
                value: '4',
                sex: 'female',
                age: 0,
                level: '2.1.1',
                home: 'No clue',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
              {
                name: 'Amaratbhai',
                value: '5',
                sex: 'male',
                age: 0,
                level: '2.1.2',
                home: 'Chandisar',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
              {
                name: 'Narmadaben',
                value: '6',
                sex: 'female',
                age: 0,
                level: '2.1.3',
                home: 'No clue',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
              {
                name: 'Ashokbhai',
                value: '7',
                sex: 'male',
                age: 0,
                level: '2.1.4',
                home: 'Chandisar',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
              {
                name: 'Ishvabhai',
                value: '8',
                sex: 'male',
                age: 0,
                level: '2.1.5',
                home: 'Chandisar',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
              {
                name: 'Maheshbhai',
                value: '9',
                sex: 'male',
                age: 0,
                level: '2.1.6',
                home: 'Chandisar',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
            ],
          },
          {
            name: 'Dalajibhai',
            sex: 'male',
            value: '10',
            age: 0,
            level: '2.2',
            home: 'Gathaman',
            spouce: 'Shantaben',
            spouceAge: 0,
            spouceHome: 'Chandisar',
            items: [
              {
                name: 'Yogeshbhai(Natubhai)',
                sex: 'male',
                value: '11',
                age: 0,
                level: '2.2.1',
                home: 'Palanpur',
                spouce: 'Madhuben',
                spouceAge: 0,
                spouceHome: 'Lukhasan',
                items: [
                  {
                    name: 'Maitri(Bittu)',
                    sex: 'female',
                    value: '12',
                    age: 0,
                    level: '2.2.1.1',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Dev',
                    sex: 'male',
                    value: '13',
                    age: 0,
                    level: '2.2.1.2',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Karan',
                    sex: 'male',
                    value: '14',
                    age: 0,
                    level: '2.2.1.3',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Ramilaben',
                sex: 'female',
                value: '15',
                age: 0,
                level: '2.2.2',
                home: 'Palanpur',
                spouce: 'Karasandas',
                spouceAge: 0,
                spouceHome: 'Palanpur',
                items: [
                  {
                    name: 'Anjali',
                    sex: 'female',
                    value: '16',
                    age: 0,
                    level: '2.2.2.1',
                    home: 'Palanpur',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Pushpaben',
                sex: 'female',
                value: '17',
                age: 0,
                level: '2.2.3',
                home: 'Palanpur',
                spouce: 'Dheerajkumar',
                spouceAge: 0,
                spouceHome: 'Zakha',
                items: [
                  {
                    name: 'Yash',
                    sex: 'male',
                    value: '18',
                    age: 0,
                    level: '2.2.3.1',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
            ],
          },
          {
            name: 'Jiviben',
            sex: 'female',
            value: '19',
            age: 0,
            level: '2.3',
            home: 'Megalvas, Palanpur',
            spouce: 'Shankarbhai',
            spouceAge: 0,
            spouceHome: 'Palanpur',
            items: [
              {
                name: 'Pareshbhai',
                sex: 'male',
                value: '20',
                age: 0,
                level: '2.3.1',
                home: 'Palanpur',
                spouce: 'Anitaben',
                spouceAge: 0,
                spouceHome: 'Palanpur',
                items: [
                  {
                    name: 'Surbhi',
                    sex: 'female',
                    value: '104',
                    age: 0,
                    dateOfBirth: '1999-06-13T00',
                    level: '2.3.1.1',
                    home: 'Palanpur',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Rishabh',
                    sex: 'male',
                    value: '105',
                    age: 0,
                    dateOfBirth: '1999-06-13T00',
                    level: '2.3.1.2',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Bhartiben',
                sex: 'female',
                value: '21',
                age: 0,
                level: '2.3.2',
                home: 'Palanpur',
                spouce: 'Kanubhai Khadaliya',
                spouceAge: 0,
                spouceHome: 'Palanpur',
                items: [
                  {
                    name: 'Priyanka',
                    sex: 'female',
                    value: '22',
                    age: 0,
                    level: '2.3.2.1',
                    home: 'Palanpur',
                    spouce: 'Abhishek',
                    spouceAge: 0,
                    spouceHome: 'Palanpur',
                    items: [
                      {
                        name: 'Parv',
                        sex: 'male',
                        value: '23',
                        age: 0,
                        level: '2.3.2.1.1',
                        home: 'Palanpur',
                        spouce: 'No clue',
                        spouceAge: 0,
                        spouceHome: 'No clue',
                      },
                    ],
                  },
                ],
              },
              {
                name: 'Atulbhai',
                sex: 'male',
                value: '24',
                age: 0,
                level: '2.3.3',
                home: 'Palanpur',
                spouce: 'Pinkyben',
                spouceAge: 0,
                spouceHome: 'Radhanpur',
                items: [
                  {
                    name: 'Om',
                    sex: 'male',
                    value: '25',
                    age: 0,
                    level: '2.3.3.1',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Kavya',
                    sex: 'female',
                    value: '26',
                    age: 0,
                    level: '2.3.3.2',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
            ],
          },
          {
            name: 'Hirabhai',
            sex: 'male',
            value: '27',
            age: 0,
            level: '2.4',
            home: 'Gathaman',
            spouce: 'Shantaben',
            spouceAge: 0,
            spouceHome: 'Madana',
            items: [
              {
                name: 'Poonam',
                sex: 'female',
                value: '28',
                age: 29,
                level: '2.4.1',
                home: 'Changvada',
                spouce: 'Hiteshkumar',
                spouceAge: 0,
                spouceHome: 'Surat',
                items: [
                  {
                    name: 'Parth',
                    sex: 'male',
                    value: '29',
                    age: 0,
                    level: '2.4.1.1',
                    home: 'Surat',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
            ],
          },
          {
            name: 'Narbhiben',
            sex: 'female',
            value: '30',
            age: 0,
            level: '2.5',
            home: 'Malan',
            spouce: 'Shankarbhai',
            spouceAge: 0,
            spouceHome: 'Malan',
            items: [
              {
                name: 'Kalpeshbhai',
                sex: 'male',
                value: '31',
                age: 0,
                level: '2.5.1',
                home: 'Malan',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
              {
                name: 'Kuntal',
                sex: 'male',
                value: '106',
                age: 0,
                level: '2.5.2',
                home: 'Malan',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
              },
            ],
          },
          {
            name: 'Bhagvanbhai',
            value: '32',
            sex: 'male',
            age: 0,
            level: '2.6',
            home: 'Gathaman',
            spouce: 'Savitaben',
            spouceAge: 0,
            spouceHome: 'Palanpur',
            items: [
              {
                name: 'Manishaben',
                value: '33',
                sex: 'female',
                age: 0,
                level: '2.6.1',
                home: 'Jalotra',
                spouce: 'Kamleshkumar',
                spouceAge: 0,
                spouceHome: 'Jalotra',
              },
              {
                name: 'Satish',
                value: '34',
                sex: 'male',
                age: 0,
                level: '2.6.2',
                home: 'Surat',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
                items: [
                  {
                    name: 'Jainil',
                    value: '35',
                    sex: 'male',
                    age: 0,
                    level: '2.6.2.1',
                    home: 'Surat',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Pradeep',
                value: '36',
                sex: 'male',
                age: 0,
                level: '2.6.3',
                home: 'Surat',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'No clue',
                items: [
                  {
                    name: 'Divam',
                    value: '37',
                    sex: 'male',
                    age: 0,
                    level: '2.6.3.1',
                    home: 'Surat',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Hetalben',
                value: '38',
                sex: 'female',
                age: 0,
                level: '2.6.4',
                home: 'Tavadiya',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'Tavadiya',
              },
            ],
          },
          {
            name: 'Narmadaben',
            sex: 'female',
            value: '39',
            age: 0,
            level: '2.7',
            home: 'Takarvada',
            spouce: 'Virchanddas',
            spouceAge: 0,
            spouceHome: 'Takarvada',
            items: [
              {
                name: 'Sonalben',
                sex: 'female',
                value: '40',
                age: 0,
                level: '2.7.1',
                home: 'Mithivav, Palanpur',
                spouce: 'Maheshkumar',
                spouceAge: 0,
                spouceHome: 'Mithivav, Palanpur',
                items: [
                  {
                    name: 'Bhavya',
                    sex: 'male',
                    value: '41',
                    age: 0,
                    level: '2.7.1.1',
                    home: 'Mithivav, Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Krithi',
                    sex: 'female',
                    value: '42',
                    age: 0,
                    level: '2.7.1.2',
                    home: 'Mithivav, Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
            ],
          },
          {
            name: 'Dineshbhai',
            sex: 'male',
            value: '43',
            age: 0,
            level: '2.8',
            home: 'Gathaman',
            spouce: 'Vimuben',
            spouceAge: 0,
            spouceHome: 'Kotda',
            items: [
              {
                name: 'Kalpanaben',
                sex: 'female',
                value: '44',
                age: 31,
                level: '2.8.1',
                home: 'Palanpur',
                spouce: 'Bipinkumar',
                spouceAge: 0,
                spouceHome: 'Meta',
                items: [
                  {
                    name: 'Het',
                    sex: 'male',
                    value: '45',
                    age: 0,
                    level: '2.8.1.1',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Piyush',
                sex: 'male',
                value: '46',
                age: 26,
                level: '2.8.2',
                home: 'Gathaman',
                spouce: 'No clue',
                spouceAge: 0,
                spouceHome: 'Meta',
              },
            ],
          },
        ],
      },
      {
        name: 'Chelabhai',
        value: '47',
        sex: 'male',
        age: 0,
        level: '3',
        home: 'Kailashnagar, Palanpur',
        spouce: 'Shantaben',
        spouceAge: 0,
        spouceHome: 'Megalvas, Palanpur',
        items: [
          {
            name: 'Devabhai',
            value: '48',
            sex: 'male',
            age: 0,
            level: '3.1',
            home: 'Kailashnagar, Palanpur',
            spouce: 'Shantaben',
            spouceAge: 0,
            spouceHome: 'Megalvas, Palanpur',
            items: [
              {
                name: 'Hiteshbhai',
                value: '49',
                sex: 'male',
                age: 0,
                level: '3.1.1',
                home: 'Kailashnagar, Palanpur',
                spouce: 'Ramilaben',
                spouceAge: 0,
                spouceHome: 'Chadotar',
                items: [
                  {
                    name: 'Tushar(Pintu)',
                    value: '50',
                    sex: 'male',
                    age: 0,
                    level: '3.1.1.1',
                    home: 'Kailashnagar, Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Daksh',
                    value: '51',
                    sex: 'male',
                    age: 0,
                    level: '3.1.1.2',
                    home: 'Kailashnagar, Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Minaben',
                value: '52',
                sex: 'female',
                age: 0,
                level: '3.1.2',
                home: 'Surat',
                spouce: 'Anilkumar',
                spouceAge: 0,
                spouceHome: 'Chadotar',
                items: [
                  {
                    name: 'Hinal',
                    value: '53',
                    sex: 'male',
                    age: 0,
                    level: '3.1.2.1',
                    home: 'Surat',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Varshil',
                    value: '54',
                    sex: 'male',
                    age: 0,
                    level: '3.1.2.2',
                    home: 'Surat',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Ranjanben',
                value: '55',
                sex: 'female',
                age: 0,
                level: '3.1.3',
                home: 'Tharad',
                spouce: 'Bharatkumar',
                spouceAge: 0,
                spouceHome: 'Tharad',
                items: [
                  {
                    name: 'Krupa',
                    value: '56',
                    sex: 'female',
                    age: 0,
                    level: '3.1.3.1',
                    home: 'Tharad',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Pranav',
                    value: '57',
                    sex: 'male',
                    age: 0,
                    level: '3.1.3.2',
                    home: 'Tharad',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Sunilbhai',
                value: '58',
                sex: 'male',
                age: 0,
                level: '3.1.4',
                home: 'Kailashnagar, Palanpur',
                spouce: 'Vimuben',
                spouceAge: 0,
                spouceHome: 'Mahi',
                items: [
                  {
                    name: 'Nisarg',
                    value: '59',
                    sex: 'male',
                    age: 0,
                    level: '3.1.4.1',
                    home: 'Kailashnagar, Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Jaydeep',
                    value: '60',
                    sex: 'male',
                    age: 0,
                    level: '3.1.4.2',
                    home: 'Kailashnagar, Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'Gamanbhai',
        value: '61',
        sex: 'male',
        age: 0,
        level: '4',
        home: 'Gathaman',
        spouce: 'Navaben',
        spouceAge: 74,
        spouceHome: 'Kant',
        items: [
          {
            name: 'Diviben',
            value: '62',
            sex: 'female',
            age: 0,
            level: '4.1',
            home: 'Mumbai',
            spouce: 'Khushalbhai',
            spouceAge: 0,
            spouceHome: 'Sagrosana',
            items: [
              {
                name: 'Dineshbhai',
                value: '63',
                sex: 'male',
                age: 0,
                level: '4.1.1',
                home: 'Mumbai',
                spouce: 'Minaben',
                spouceAge: 0,
                spouceHome: 'Palanpur',
                items: [
                  {
                    name: 'Harshil',
                    value: '64',
                    sex: 'male',
                    age: 0,
                    level: '4.1.1.1',
                    home: 'Mumbai',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Sneha',
                    value: '65',
                    sex: 'female',
                    age: 0,
                    level: '4.1.1.2',
                    home: 'Mumbai',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Mukeshbhai',
                value: '66',
                sex: 'male',
                age: 0,
                level: '4.1.2',
                home: 'Mumbai',
                spouce: 'Dharaben',
                spouceAge: 0,
                spouceHome: 'Laxmipura',
                items: [
                  {
                    name: 'Hetu',
                    value: '67',
                    sex: 'female',
                    age: 0,
                    level: '4.1.2.1',
                    home: 'Mumbai',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Ishita',
                    value: '68',
                    sex: 'female',
                    age: 0,
                    level: '4.1.2.2',
                    home: 'Mumbai',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Anitaben',
                value: '69',
                sex: 'male',
                age: 0,
                level: '4.1.3',
                home: 'Mumbai',
                spouce: 'Pravinkumar',
                spouceAge: 0,
                spouceHome: 'Gagalasan',
                items: [
                  {
                    name: 'Dhruv',
                    value: '70',
                    sex: 'male',
                    age: 0,
                    level: '4.1.3.1',
                    home: 'Mumbai',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                  {
                    name: 'Sujal',
                    value: '71',
                    sex: 'male',
                    age: 0,
                    level: '4.1.3.2',
                    home: 'Mumbai',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
            ],
          },
          {
            name: 'Hargovindbhai',
            value: '72',
            sex: 'male',
            age: 0,
            level: '4.2',
            home: 'Gathaman',
            spouce: 'Nayanaben',
            spouceAge: 0,
            spouceHome: 'Sagrosana',
            items: [
              {
                name: 'Nitinbhai',
                value: '73',
                sex: 'male',
                age: 0,
                level: '4.2.1',
                home: 'Palanpur',
                spouce: 'Archanaben',
                spouceAge: 0,
                spouceHome: 'Meta',
                items: [
                  {
                    name: 'Vanshika',
                    value: '74',
                    sex: 'female',
                    age: 0,
                    level: '4.2.1.1',
                    home: 'Palanpur',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Nirav',
                value: '75',
                sex: 'male',
                age: 0,
                level: '4.2.2',
                home: 'Gathaman',
                spouce: 'Nikitaben',
                spouceAge: 0,
                spouceHome: 'Tenivada',
                items: [
                  {
                    name: 'Heer',
                    value: '76',
                    sex: 'female',
                    age: 0,
                    level: '4.2.2.1',
                    home: 'Gathaman',
                    spouce: 'No clue',
                    spouceAge: 0,
                    spouceHome: 'No clue',
                  },
                ],
              },
              {
                name: 'Pravinaben',
                value: '77',
                sex: 'female',
                age: 0,
                level: '4.2.3',
                home: 'Palanpur',
                spouce: 'Jayeshkumar',
                spouceAge: 0,
                spouceHome: 'Majadar',
                items: [
                  {
                    name: 'Preksha(Pari)',
                    value: '78',
                    sex: 'female',
                    age: 0,
                    level: '4.2.3.1',
                    home: 'Palanpur',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                  },
                  {
                    name: 'Neel',
                    value: '79',
                    sex: 'male',
                    age: 0,
                    level: '4.2.3.2',
                    home: 'Palanpur',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                  },
                ],
              },
            ],
          },
          {
            name: 'Prabhubhai',
            value: '80',
            sex: 'male',
            age: 57,
            level: '4.3',
            dateOfBirth: '1963-01-16T00',
            spouceDateOfBirth: '1967-01-04T00',
            home: 'Palanpur',
            spouce: 'Bharatiben',
            spouceAge: 53,
            spouceHome: 'Mithivav, Palanpur',
            imagePath: require('../src/images/80.png'),
            imagePathSpouse: require('../src/images/80S.png'),
            items: [
              {
                name: 'Vipul',
                value: '81',
                sex: 'male',
                age: 31,
                dateOfBirth: '1989-12-13T00',
                spouceDateOfBirth: '1989-08-01T00',
                level: '4.3.1',
                home: 'Canada',
                spouce: 'Harnisha',
                spouceAge: 31,
                spouceHome: 'Junagadh',
                imagePath: require('../src/images/81.png'),
                imagePathSpouse: require('../src/images/81S.png'),
                items: [
                  {
                    name: 'Viha',
                    value: '82',
                    sex: 'female',
                    dateOfBirth: '2020-04-24T00',
                    age: 0,
                    level: '4.3.1.1',
                    home: 'Canada',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                    imagePath: require('../src/images/82.png'),
                  },
                ],
              },
              {
                name: 'Vishal',
                value: '83',
                sex: 'male',
                age: 28,
                dateOfBirth: '1991-07-09T00',
                spouceDateOfBirth: '1991-01-19T00',
                level: '4.3.2',
                home: 'Australia',
                spouce: 'Sonali',

                spouceAge: 29,
                spouceHome: 'Palanpur',
                imagePath: require('../src/images/83.png'),
                imagePathSpouse: require('../src/images/83S.png'),
              },
              {
                name: 'Chirag',
                value: '84',
                sex: 'male',
                age: 25,
                dateOfBirth: '1994-01-19T00',
                spouceDateOfBirth: '1996-05-02T00',
                level: '4.3.3',
                home: 'Rajpipla',
                spouce: 'Pooja',
                spouceAge: 24,
                spouceHome: 'Vadgam',
                imagePath: require('../src/images/84.png'),
                imagePathSpouse: require('../src/images/84S.png'),
              },
            ],
          },
          {
            name: 'Madhuben',
            value: '85',
            sex: 'female',
            age: 0,
            level: '4.4',
            home: 'Kotda',
            spouce: 'Dahyalal',
            spouceAge: 0,
            spouceHome: 'Kotda',
            items: [
              {
                name: 'Divyeshbhai(Deepakbhai)',
                value: '86',
                sex: 'male',
                age: 0,
                level: '4.4.1',
                home: 'Kotda',
                spouce: 'Bhartiben',
                spouceAge: 0,
                spouceHome: 'Pirojpura',
                items: [
                  {
                    name: 'Trusha',
                    value: '87',
                    sex: 'female',
                    age: 0,
                    level: '4.4.1.1',
                    home: 'Kotda',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                  },
                  {
                    name: 'Zeel',
                    value: '88',
                    sex: 'male',
                    age: 0,
                    level: '4.4.1.2',
                    home: 'Kotda',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                  },
                ],
              },
              {
                name: 'Bharatbhai',
                value: '89',
                sex: 'male',
                age: 0,
                level: '4.4.2',
                home: 'Kotda',
                spouce: 'Kapilaben',
                spouceAge: 0,
                spouceHome: 'Changvada',
                items: [
                  {
                    name: 'Mahi',
                    value: '90',
                    sex: 'female',
                    age: 0,
                    level: '4.4.2.1',
                    home: 'Kotda',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                  },
                  {
                    name: 'Ishani',
                    value: '91',
                    sex: 'female',
                    age: 0,
                    level: '4.4.2.2',
                    home: 'Kotda',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                  },
                ],
              },
              {
                name: 'Binaben',
                value: '92',
                sex: 'female',
                age: 0,
                level: '4.4.3',
                home: 'Gandhinagar',
                spouce: 'Ronakkumar',
                spouceAge: 0,
                spouceHome: 'Gandhinagar',
                items: [
                  {
                    name: 'Vihan',
                    value: '93',
                    sex: 'male',
                    age: 0,
                    level: '4.4.3.1',
                    home: 'Gandhinagar',
                    spouce: '',
                    spouceAge: 0,
                    spouceHome: '',
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        name: 'Avaliben',
        value: '94',
        sex: 'female',
        age: 0,
        level: '5',
        home: 'Gathaman',
        spouce: 'No clue',
        spouceAge: 0,
        spouceHome: 'Madana',
        items: [
          {
            name: 'Kanjibhai',
            value: '95',
            sex: 'male',
            age: 0,
            level: '5.1',
            home: 'Takarvada',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Kevalbhai',
            value: '96',
            sex: 'male',
            age: 0,
            level: '5.2',
            home: 'Takarvada',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Ganeshbhai',
            value: '97',
            sex: 'male',
            age: 0,
            level: '5.3',
            home: 'Takarvada',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Menaben',
            value: '98',
            sex: 'female',
            age: 0,
            level: '5.4',
            home: 'No clue',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Ambarambhai',
            value: '99',
            sex: 'male',
            age: 0,
            level: '5.5',
            home: 'Mumbai',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Jamanaben',
            value: '100',
            sex: 'fmale',
            age: 0,
            level: '5.6',
            home: 'No clue',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Chamanbhai',
            value: '101',
            sex: 'male',
            age: 0,
            level: '5.7',
            home: 'Takarvada',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Narmadaben',
            value: '102',
            sex: 'female',
            age: 0,
            level: '5.8',
            home: 'No clue',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
          {
            name: 'Vasantbhai',
            value: '103',
            sex: 'male',
            age: 0,
            level: '5.9',
            home: 'Palanpur',
            spouce: 'No clue',
            spouceAge: 0,
            spouceHome: 'No clue',
          },
        ],
      },
    ],
  },
];
// last value:106
